VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iSelection"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public ChildShapeRange As iShapeRange
Public HasChildShapeRange As Boolean
Public ShapeRange As iShapeRange
Public SlideRange As iSlideRange
'Public TextRange As iTextRange
Public TextRange2 As iTextRange2
Public iType As PpSelectionType ' Type
