VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iTextFrame2"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Application As Object
Public AutoSize As MsoAutoSize
'Public Column As iTextColumn2
Public Creator As Long
Public HasText As MsoTriState
Public HorizontalAnchor As MsoHorizontalAnchor
Public MarginBottom As Single
Public MarginLeft As Single
Public MarginRight As Single
Public MarginTop As Single
Public NoTextRotation As MsoTriState
Public Orientation As MsoTextOrientation
Public Parent As Object
Public PathFormat As MsoPathFormat
'Public Ruler As iRuler2
Public TextRange As iTextRange2
'Public ThreeD As iThreeDFormat
Public VerticalAnchor As MsoVerticalAnchor
Public WarpFormat As MsoWarpFormat
Public WordArtFormat As MsoPresetTextEffect
Public WordWrap As MsoTriState


'ActiveWindow.Selection.ShapeRange.TextFrame2.WordWrap

