VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iTextFrame"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'SUPERSEDED WITH ITEXTFRAME2

Public Application As Object
Public AutoSize As PpAutoSize
Public Creator As Long
Public HasText As MsoTriState
Public HorizontalAnchor As MsoHorizontalAnchor
Public MarginBottom As Single
Public MarginLeft As Single
Public MarginRight As Single
Public MarginTop As Single
Public Orientation As MsoTextOrientation
Public Parent As Object
'Public Ruler As iRuler
Public TextRange As iTextRange
Public VerticalAnchor As MsoVerticalAnchor
Public WordWrap As MsoTriState


'ActiveWindow.Selection.ShapeRange.TextFrame.WordWrap


