VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iTextRange"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'SUPERSEDED WITH ITEXTRANGE2

'Public ActionSettings As iActionSettings
Public Application As iApplication
Public BoundHeight As Single
Public BoundLeft As Single
Public BoundTop As Single
Public BoundWidth As Single
Public Count As Long
Public Font As IFont
Public IndentLevel As Long
Public LanguageID As MsoLanguageID
Public length As Long
'Public ParagraphFormat As iParagraphFormat
Public Parent As Object
Public Start As Long
Public Text As String

'ActiveWindow.Selection.ShapeRange.TextFrame2.TextRange.Start

