VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iCustomLayouts"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Function Add(Index As Long) As CustomLayout
'Property Application As Application
'Property Count As Long
'Function Item(Index) As CustomLayout
'Property Parent As Object
'Function Paste([Index As Long = -1]) As CustomLayout
