VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iCustomLayout"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Property Application As Application
'Property Background As ShapeRange
'Sub Copy()
'Property CustomerData As CustomerData
'Sub Cut()
'Sub Delete()
'Property Design As Design
'Property DisplayMasterShapes As MsoTriState
'Function Duplicate() As CustomLayout
'Property FollowMasterBackground As MsoTriState
'Property Guides As Guides
'Property HeadersFooters As HeadersFooters
'Property Height As Single
'Property Hyperlinks As Hyperlinks
'Property Index As Long
'Property MatchingName As String
'Sub MoveTo(toPos As Long)
'Property Name As String
'Property Parent As Object
'Property Preserved As MsoTriState
'Sub Select()
'Property Shapes As Shapes
'Property SlideShowTransition As SlideShowTransition
'Property ThemeColorScheme As ThemeColorScheme
'Property TimeLine As TimeLine
'Property Width As Single

Sub init(iCustomLayout As CustomLayout)

End Sub

Sub DefaultValues()

End Sub
